"""Remedy configuration system.

Loads config from TOML/YAML files (e.g. ~/.remedy/config.toml),
environment variable overrides, and CLI arguments. Provides a single
merged config for all subsystems.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any, Optional

import yaml

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]

from remedy.models import AgentConfig, ChannelKind


CONFIG_PATHS = [
    Path("~/.remedy/config.toml"),
    Path("~/.remedy/config.yaml"),
    Path("remedy.toml"),
    Path("remedy.yaml"),
]

ENV_PREFIX = "REMEDY_"


def load_config(path: Optional[Path] = None) -> dict[str, Any]:
    """Load config from a file, auto-detecting format (TOML or YAML)."""
    if path is None:
        for p in CONFIG_PATHS:
            expanded = p.expanduser().resolve()
            if expanded.exists():
                path = expanded
                break

    if path is None:
        return {}

    path = Path(path).expanduser().resolve()
    if not path.exists():
        return {}

    content = path.read_text(encoding="utf-8")

    if path.suffix in (".toml", ".tml"):
        return tomllib.loads(content)
    elif path.suffix in (".yaml", ".yml"):
        return yaml.safe_load(content) or {}
    elif "---" in content[:100] or path.suffix == ".yaml":
        return yaml.safe_load(content) or {}
    else:
        return tomllib.loads(content)


def load_env_overrides(base: dict[str, Any]) -> dict[str, Any]:
    """Apply environment variable overrides.

    Maps REMEDY_NAME=foo to config["name"] = "foo"
    Maps REMEDY_LOG_LEVEL=DEBUG to config["log"]["level"] = "DEBUG"
    """
    result = dict(base)
    for key, value in os.environ.items():
        if not key.startswith(ENV_PREFIX):
            continue
        config_key = key[len(ENV_PREFIX):].lower()
        parts = config_key.split("__")
        if len(parts) == 1:
            result[parts[0]] = _coerce(value)
        else:
            current = result
            for part in parts[:-1]:
                if part not in current:
                    current[part] = {}
                current = current[part]
            current[parts[-1]] = _coerce(value)
    return result


def _coerce(value: str) -> Any:
    if value.lower() in ("true", "yes", "1"):
        return True
    if value.lower() in ("false", "no", "0"):
        return False
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        pass
    return value


def resolve_config(
    config_path: Optional[Path] = None,
    home_dir: Optional[str] = None,
    env_overrides: bool = True,
) -> dict[str, Any]:
    """Load and resolve full configuration.

    Priority: env vars > config file > defaults.
    """
    config = load_config(config_path)
    if env_overrides:
        config = load_env_overrides(config)
    if home_dir:
        config["home_dir"] = home_dir
    return config


def config_to_agent_config(config: dict[str, Any]) -> AgentConfig:
    """Convert a config dict to a validated AgentConfig model."""
    return AgentConfig(
        name=config.get("name", "Remedy"),
        persona=config.get("persona", "default"),
        home_dir=config.get("home_dir", "~/.remedy"),
        skills_dir=config.get("skills_dir", []),
        memory_db_path=config.get("memory_db_path"),
        enabled_channels=[ChannelKind(c) for c in config.get("enabled_channels", [])],
        mcp_servers=config.get("mcp_servers", []),
        allow_skill_creation=config.get("allow_skill_creation", True),
        auto_approve_threshold=config.get("auto_approve_threshold", 0.8),
        log_level=config.get("log_level", "INFO"),
        sarcasm_mode=config.get("sarcasm_mode", False),
        llm_api_key=config.get("llm_api_key", os.environ.get("REMEDY_LLM_API_KEY", "")),
        llm_model=config.get("llm_model", os.environ.get("REMEDY_LLM_MODEL", "gpt-4o-mini")),
        llm_base_url=config.get("llm_base_url", os.environ.get("REMEDY_LLM_BASE_URL", "https://api.openai.com/v1")),
    )


def generate_default_config(home_dir: Path) -> str:
    """Generate a default TOML config file content."""
    return f"""# Remedy AI Configuration
# Generated by remedy config init

name = "Remedy"
persona = "default"
home_dir = "{home_dir.as_posix()}"

# Search paths for bundled + user skills
skills_dir = []

# SQLite memory database
memory_db_path = "{home_dir.joinpath('memory.db').as_posix()}"

# Channels to enable: cli, telegram, discord, slack, web, api
enabled_channels = ["cli"]

# MCP server configurations
mcp_servers = []

# Learning loop
allow_skill_creation = true
auto_approve_threshold = 0.8

# Logging
log_level = "INFO"

[gateway]
heartbeat_interval = 60
rate_limit = 120

[execution]
default_timeout = 30
max_retries = 3
retry_backoff = 1.0

[telegram]
bot_token = ""

[discord]
bot_token = ""
channel_id = ""

[slack]
bot_token = ""
channel_id = ""
"""


def create_default_config(home_dir: Optional[Path] = None) -> Path:
    """Create a default config file in the home directory."""
    hd = (home_dir or Path("~/.remedy")).expanduser()
    hd.mkdir(parents=True, exist_ok=True)
    config_path = hd / "config.toml"
    if not config_path.exists():
        config_path.write_text(generate_default_config(hd), encoding="utf-8")
    return config_path
