package httpapi

import (
	"regexp"
	"strconv"
	"strings"
)

var (
	frontmatterRE = regexp.MustCompile(`(?s)^---\r?\n(.*?)\r?\n---\r?\n?`)
	tokenSplitRE  = regexp.MustCompile(`[^a-z0-9]+`)
)

// skillFM is the subset of SKILL.md frontmatter the HTTP surface needs.
type skillFM struct {
	Name          string
	Description   string
	Version       string
	Author        string
	Status        string
	Tags          []string
	AutoGenerated bool
	Quarantine    bool
	Lifecycle     string
	EffortWeight  float64
	EffortBand    string
	LibraryID     string
	Source        string
	SuccessRate   *float64
	RawMeta       map[string]string
}

func parseSkillFrontmatter(raw string) (skillFM, string, bool) {
	m := frontmatterRE.FindStringSubmatch(raw)
	if m == nil {
		return skillFM{}, strings.TrimSpace(raw), false
	}
	body := strings.TrimSpace(raw[len(m[0]):])
	fm := parseFrontmatterBlock(m[1])
	return fm, body, true
}

func parseFrontmatterBlock(block string) skillFM {
	lines := splitYAMLLines(block)
	vals := map[string]string{}
	var i int
	for i < len(lines) {
		line := lines[i]
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			i++
			continue
		}
		indent := countIndent(line)
		trimmed := strings.TrimSpace(line)
		if indent > 0 {
			i++
			continue
		}
		key, rest, ok := splitKV(trimmed)
		if !ok {
			i++
			continue
		}
		key = strings.ToLower(key)
		if key == "metadata" && (rest == "" || rest == "|" || rest == ">") {
			meta, next := parseIndentedMap(lines, i+1, indent)
			for mk, mv := range meta {
				vals["metadata."+strings.ToLower(mk)] = mv
			}
			i = next
			continue
		}
		if rest == ">" || rest == "|" {
			folded, next := parseFoldedScalar(lines, i+1, indent)
			vals[key] = folded
			i = next
			continue
		}
		if rest == "" {
			// Possibly a nested map we do not need; skip indented block.
			next := i + 1
			for next < len(lines) && countIndent(lines[next]) > indent && strings.TrimSpace(lines[next]) != "" {
				next++
			}
			i = next
			continue
		}
		vals[key] = unquoteYAML(rest)
		i++
	}

	out := skillFM{
		Name:        strings.TrimSpace(vals["name"]),
		Description: strings.TrimSpace(vals["description"]),
		Version:     strings.TrimSpace(vals["version"]),
		Author:      strings.TrimSpace(vals["author"]),
		Status:      strings.ToLower(strings.TrimSpace(vals["status"])),
		Tags:        parseYAMLStringList(vals["tags"]),
		RawMeta:     map[string]string{},
	}
	if out.Version == "" {
		out.Version = "1.0.0"
	}
	for k, v := range vals {
		if strings.HasPrefix(k, "metadata.") {
			out.RawMeta[strings.TrimPrefix(k, "metadata.")] = v
		}
	}
	// Promote common top-level keys (Python loader parity).
	for _, k := range []string{
		"auto_generated", "quarantine", "lifecycle", "effort_weight",
		"effort_band", "library_id", "source", "success_rate", "trust",
	} {
		if _, ok := out.RawMeta[k]; !ok {
			if v, ok := vals[k]; ok {
				out.RawMeta[k] = v
			}
		}
	}
	out.AutoGenerated = truthyYAML(out.RawMeta["auto_generated"])
	out.Quarantine = truthyYAML(out.RawMeta["quarantine"])
	out.Lifecycle = strings.TrimSpace(out.RawMeta["lifecycle"])
	out.EffortBand = strings.TrimSpace(out.RawMeta["effort_band"])
	out.LibraryID = strings.TrimSpace(out.RawMeta["library_id"])
	out.Source = strings.TrimSpace(out.RawMeta["source"])
	if w := strings.TrimSpace(out.RawMeta["effort_weight"]); w != "" {
		if f, err := strconv.ParseFloat(w, 64); err == nil {
			out.EffortWeight = f
		}
	}
	if r := strings.TrimSpace(out.RawMeta["success_rate"]); r != "" {
		if f, err := strconv.ParseFloat(r, 64); err == nil {
			out.SuccessRate = &f
		}
	}
	return out
}

func splitYAMLLines(block string) []string {
	block = strings.ReplaceAll(block, "\r\n", "\n")
	return strings.Split(block, "\n")
}

func countIndent(line string) int {
	n := 0
	for _, r := range line {
		if r == ' ' {
			n++
			continue
		}
		if r == '\t' {
			n += 2
			continue
		}
		break
	}
	return n
}

func splitKV(line string) (key, rest string, ok bool) {
	if i := strings.IndexByte(line, ':'); i > 0 {
		key = strings.TrimSpace(line[:i])
		rest = strings.TrimSpace(line[i+1:])
		if key != "" {
			return key, rest, true
		}
	}
	return "", "", false
}

func parseFoldedScalar(lines []string, start, parentIndent int) (string, int) {
	var parts []string
	i := start
	for i < len(lines) {
		line := lines[i]
		if strings.TrimSpace(line) == "" {
			if i+1 < len(lines) && countIndent(lines[i+1]) > parentIndent {
				parts = append(parts, "")
				i++
				continue
			}
			break
		}
		if countIndent(line) <= parentIndent {
			break
		}
		parts = append(parts, strings.TrimSpace(line))
		i++
	}
	return strings.TrimSpace(strings.Join(parts, " ")), i
}

func parseIndentedMap(lines []string, start, parentIndent int) (map[string]string, int) {
	out := map[string]string{}
	i := start
	for i < len(lines) {
		line := lines[i]
		if strings.TrimSpace(line) == "" {
			i++
			continue
		}
		ind := countIndent(line)
		if ind <= parentIndent {
			break
		}
		trimmed := strings.TrimSpace(line)
		key, rest, ok := splitKV(trimmed)
		if !ok {
			i++
			continue
		}
		if rest == ">" || rest == "|" {
			folded, next := parseFoldedScalar(lines, i+1, ind)
			out[key] = folded
			i = next
			continue
		}
		out[key] = unquoteYAML(rest)
		i++
	}
	return out, i
}

func unquoteYAML(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			inner := s[1 : len(s)-1]
			inner = strings.ReplaceAll(inner, `\"`, `"`)
			inner = strings.ReplaceAll(inner, `\'`, `'`)
			return inner
		}
	}
	if i := strings.Index(s, " #"); i >= 0 {
		s = strings.TrimSpace(s[:i])
	}
	return s
}

func parseYAMLStringList(raw string) []string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil
	}
	if strings.HasPrefix(raw, "[") && strings.HasSuffix(raw, "]") {
		inner := strings.TrimSpace(raw[1 : len(raw)-1])
		if inner == "" {
			return nil
		}
		parts := strings.Split(inner, ",")
		out := make([]string, 0, len(parts))
		for _, p := range parts {
			p = unquoteYAML(strings.TrimSpace(p))
			if p != "" {
				out = append(out, p)
			}
		}
		return out
	}
	return []string{unquoteYAML(raw)}
}

func truthyYAML(v string) bool {
	switch strings.ToLower(strings.TrimSpace(v)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func tokenizeSkillText(text string) map[string]struct{} {
	parts := tokenSplitRE.Split(strings.ToLower(text), -1)
	out := make(map[string]struct{}, len(parts))
	for _, p := range parts {
		if len(p) >= 2 {
			out[p] = struct{}{}
		}
	}
	return out
}
