package httpapi

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// skillRecord is one discovered SKILL.md package.
type skillRecord struct {
	Name          string
	Description   string
	Version       string
	Author        string
	Kind          string
	Status        string
	Tags          []string
	EffortWeight  float64
	EffortBand    string
	AutoGenerated bool
	Quarantine    bool
	SuccessRate   *float64
	Path          string
	Dir           string
	Body          string
	Lifecycle     string
	LibraryID     string
	Source        string
	Related       []string
}

func (s *Server) skillsHome() string {
	return ResolveHomeDir(s.homeDir)
}

func (s *Server) discoverSkills() []skillRecord {
	home := s.skillsHome()
	userRoot := filepath.Join(home, "skills")
	seedRoots := skillSeedRoots(home)
	// Packaged installs often have no cwd checkout — seed missing curated
	// skills into ~/.remedy/skills (Python SkillRegistry.discover_defaults parity).
	seedMissingUserSkills(seedRoots, userRoot)

	byName := map[string]skillRecord{}
	for _, root := range seedRoots {
		for _, rec := range loadSkillsFromRoot(root) {
			byName[rec.Name] = rec
		}
	}
	for _, rec := range loadSkillsFromRoot(userRoot) {
		byName[rec.Name] = rec
	}
	out := make([]skillRecord, 0, len(byName))
	for _, rec := range byName {
		out = append(out, applyDefaultSkillStatus(rec))
	}
	sort.Slice(out, func(i, j int) bool {
		return strings.ToLower(out[i].Name) < strings.ToLower(out[j].Name)
	})
	return out
}

func seedMissingUserSkills(seedRoots []string, userRoot string) {
	if strings.TrimSpace(userRoot) == "" {
		return
	}
	_ = os.MkdirAll(userRoot, 0o700)
	for _, root := range seedRoots {
		entries, err := os.ReadDir(root)
		if err != nil {
			continue
		}
		for _, ent := range entries {
			if !ent.IsDir() || strings.HasPrefix(ent.Name(), ".") {
				continue
			}
			src := filepath.Join(root, ent.Name())
			if !fileExists(filepath.Join(src, "SKILL.md")) {
				continue
			}
			dst := filepath.Join(userRoot, ent.Name())
			if dirExists(dst) {
				continue
			}
			_ = copySkillDir(src, dst)
		}
	}
}

func copySkillDir(src, dst string) error {
	if err := os.MkdirAll(dst, 0o700); err != nil {
		return err
	}
	return filepath.WalkDir(src, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o700)
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, raw, 0o600)
	})
}

func (s *Server) skillsCount() int {
	return len(s.discoverSkills())
}

func (s *Server) findSkill(name string) (skillRecord, bool) {
	name = strings.TrimSpace(name)
	if name == "" {
		return skillRecord{}, false
	}
	for _, rec := range s.discoverSkills() {
		if strings.EqualFold(rec.Name, name) {
			return rec, true
		}
	}
	return skillRecord{}, false
}

func applyDefaultSkillStatus(rec skillRecord) skillRecord {
	st := strings.ToLower(strings.TrimSpace(rec.Status))
	if st == "disabled" || st == "deprecated" || st == "archived" {
		rec.Status = st
		return rec
	}
	if rec.AutoGenerated || rec.Quarantine {
		if st == "" {
			rec.Status = "discovered"
		} else {
			rec.Status = st
		}
		return rec
	}
	rec.Status = "active"
	return rec
}

func skillSeedRoots(home string) []string {
	seen := map[string]struct{}{}
	var roots []string
	add := func(p string) {
		p = strings.TrimSpace(p)
		if p == "" {
			return
		}
		abs, err := filepath.Abs(p)
		if err != nil {
			abs = p
		}
		if st, err := os.Stat(abs); err != nil || !st.IsDir() {
			return
		}
		if _, ok := seen[abs]; ok {
			return
		}
		seen[abs] = struct{}{}
		roots = append(roots, abs)
	}

	if dev := strings.TrimSpace(os.Getenv("REMEDY_DEV_ROOT")); dev != "" {
		add(filepath.Join(dev, "src", "remedy", "bundled_skills"))
		add(filepath.Join(dev, "skills"))
	}

	// Packaged desktop: skills may sit next to remedy-runtime.exe / resources.
	if exe, err := os.Executable(); err == nil && strings.TrimSpace(exe) != "" {
		here := filepath.Dir(exe)
		for i := 0; i < 4; i++ {
			add(filepath.Join(here, "bundled_skills"))
			add(filepath.Join(here, "skills"))
			add(filepath.Join(here, "resources", "bundled_skills"))
			add(filepath.Join(here, "resources", "skills"))
			parent := filepath.Dir(here)
			if parent == here {
				break
			}
			here = parent
		}
	}

	cwd, err := os.Getwd()
	if err == nil && cwd != "" {
		here := cwd
		for i := 0; i < 6; i++ {
			bundled := filepath.Join(here, "src", "remedy", "bundled_skills")
			add(bundled)
			// Only treat ./skills as a seed root inside a Remedy checkout.
			// Walking TempDir parents must not pick up %USERPROFILE%/skills.
			isRepo := fileExists(filepath.Join(here, "pyproject.toml")) &&
				dirExists(filepath.Join(here, "src", "remedy"))
			if isRepo || dirExists(bundled) {
				add(filepath.Join(here, "skills"))
			}
			if isRepo {
				break
			}
			parent := filepath.Dir(here)
			if parent == here {
				break
			}
			here = parent
		}
	}

	_ = home // user skills scanned separately (wins on collision)
	return roots
}

func loadSkillsFromRoot(root string) []skillRecord {
	root = strings.TrimSpace(root)
	if root == "" || !dirExists(root) {
		return nil
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil
	}
	var out []skillRecord
	for _, ent := range entries {
		if !ent.IsDir() || strings.HasPrefix(ent.Name(), ".") {
			continue
		}
		dir := filepath.Join(root, ent.Name())
		if rec, ok := loadSkillDir(dir); ok {
			out = append(out, rec)
		}
	}
	return out
}

func loadSkillDir(dir string) (skillRecord, bool) {
	md := filepath.Join(dir, "SKILL.md")
	raw, err := os.ReadFile(md)
	if err != nil {
		return skillRecord{}, false
	}
	fm, body, ok := parseSkillFrontmatter(string(raw))
	if !ok || strings.TrimSpace(fm.Name) == "" {
		return skillRecord{}, false
	}
	abs, _ := filepath.Abs(dir)
	rec := skillRecord{
		Name:          strings.TrimSpace(fm.Name),
		Description:   fm.Description,
		Version:       fm.Version,
		Author:        fm.Author,
		Kind:          "native",
		Status:        fm.Status,
		Tags:          append([]string(nil), fm.Tags...),
		EffortWeight:  fm.EffortWeight,
		EffortBand:    fm.EffortBand,
		AutoGenerated: fm.AutoGenerated,
		Quarantine:    fm.Quarantine,
		SuccessRate:   fm.SuccessRate,
		Path:          abs,
		Dir:           abs,
		Body:          body,
		Lifecycle:     fm.Lifecycle,
		LibraryID:     fm.LibraryID,
		Source:        fm.Source,
		Related:       []string{},
	}
	return rec, true
}

func skillToPublic(rec skillRecord) map[string]any {
	tags := rec.Tags
	if tags == nil {
		tags = []string{}
	}
	related := rec.Related
	if related == nil {
		related = []string{}
	}
	row := map[string]any{
		"name":                rec.Name,
		"description":         rec.Description,
		"version":             rec.Version,
		"kind":                rec.Kind,
		"status":              rec.Status,
		"tags":                tags,
		"effort_weight":       rec.EffortWeight,
		"auto_generated":      rec.AutoGenerated,
		"quarantine":          rec.Quarantine,
		"path":                rec.Path,
		"related":             related,
		"activations_session": 0,
	}
	if rec.EffortBand != "" {
		row["effort_band"] = rec.EffortBand
	} else {
		row["effort_band"] = nil
	}
	if rec.Lifecycle != "" {
		row["lifecycle"] = rec.Lifecycle
	} else {
		row["lifecycle"] = nil
	}
	if rec.SuccessRate != nil {
		row["success_rate"] = *rec.SuccessRate
	} else {
		row["success_rate"] = nil
	}
	return row
}

func filterSkills(skills []skillRecord, q string, limit int) []skillRecord {
	if limit <= 0 {
		limit = 200
	}
	if limit > 500 {
		limit = 500
	}
	q = strings.TrimSpace(q)
	if q == "" {
		if len(skills) > limit {
			return skills[:limit]
		}
		return skills
	}
	ql := strings.ToLower(q)
	qTokens := tokenizeSkillText(q)
	type scored struct {
		rec   skillRecord
		score float64
	}
	var hits []scored
	for _, rec := range skills {
		nameL := strings.ToLower(rec.Name)
		descL := strings.ToLower(rec.Description)
		score := 0.0
		if strings.Contains(nameL, ql) {
			score += 3
		}
		if strings.Contains(descL, ql) {
			score += 1.5
		}
		for _, tag := range rec.Tags {
			if strings.Contains(strings.ToLower(tag), ql) {
				score += 1
			}
		}
		nameTok := tokenizeSkillText(strings.ReplaceAll(rec.Name, "-", " "))
		overlap := 0
		for t := range qTokens {
			if _, ok := nameTok[t]; ok {
				overlap++
			}
		}
		score += float64(overlap)
		if score > 0 {
			hits = append(hits, scored{rec, score})
		}
	}
	sort.SliceStable(hits, func(i, j int) bool {
		if hits[i].score != hits[j].score {
			return hits[i].score > hits[j].score
		}
		return strings.ToLower(hits[i].rec.Name) < strings.ToLower(hits[j].rec.Name)
	})
	if len(hits) > limit {
		hits = hits[:limit]
	}
	out := make([]skillRecord, len(hits))
	for i, h := range hits {
		out[i] = h.rec
	}
	return out
}

func dirExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && st.IsDir()
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}
