"""ctypes prototypes for the ``remedy_core`` host surface (ABI 5).

This package is the one place Python describes the C ABI declared in
``native/zig/include/remedy_core.h``. Every export is a thin call into the
library: marshal arguments, check Status, free Zig-owned buffers, return plain
Python values. No soft unsigned fallbacks on authorized spawns.

Windows: host + UIA + ConPTY. Linux: host (X11/XTest) + AT-SPI a11y snapshot.
``native()`` selects ``desktop_win`` / ``desktop_common`` (POSIX facade).
"""

from __future__ import annotations

import sys
from types import ModuleType

from ._conpty import (
    CONPTY_PIPE_STDIN,
    CONPTY_PIPE_STDOUT,
    _ConPTYProcess,
    _HandleStream,
    _spawn_conpty_sync,
    conpty_available,
    conpty_close,
    conpty_close_pipe,
    conpty_kill,
    conpty_poll,
    conpty_read,
    conpty_spawn,
    conpty_write,
    spawn_conpty,
    spawn_conpty_process,
    spawn_conpty_supported,
)
from ._core import (
    MOUSE_LEFT,
    MOUSE_MIDDLE,
    MOUSE_RIGHT,
    STATUS_ACCESS_DENIED,
    STATUS_INVALID_ARGUMENT,
    STATUS_OK,
    STATUS_OPERATION_FAILED,
    STATUS_UNSUPPORTED,
    WAIT_FOREVER,
    WINDOW_CLOSE,
    WINDOW_MAXIMIZE,
    WINDOW_MINIMIZE,
    WINDOW_MOVE_RESIZE,
    WINDOW_RESTORE,
    Capture,
    HostError,
    _lib,
    available,
)
from ._host import (
    capture_region,
    capture_virtual_screen,
    clipboard_get_text,
    clipboard_set_text,
    dpi_awareness_enable,
    encode_png,
    find_child_hwnd,
    focus_window,
    foreground_window,
    key_combo,
    key_hold,
    list_monitors,
    list_windows,
    manage_window,
    mouse_button,
    mouse_click,
    mouse_drag,
    mouse_move,
    mouse_scroll,
    print_window,
    process_close,
    process_kill_tree,
    process_spawn_hidden,
    process_wait,
    type_text,
    virtual_screen_rect,
    vk_key_scan,
    window_class,
    window_rect,
)
from ._ir import (
    _find_rg,
    _pwsh_exe,
    _python_exe,
    host_op_prepare,
    looks_like_powershell,
    rewrite_posix_argv,
    translate_posix_to_host,
)
from ._meta import (
    default_script_lang,
    diagnose_host_failure,
    dialect_format_line,
    dialect_load,
    dialect_probe,
    dialect_record_success,
    resolve_which,
    stretch_format_line,
    stretch_format_whoami,
    stretch_home,
    stretch_load,
    stretch_needs,
)
from ._policy import (
    CAPABILITY_TOKEN_SIZE,
    DEFAULT_SPAWN_SCOPE,
    DEFAULT_SPAWN_SUBJECT,
    OWNER_CHECKPOINT_RIGHT,
    PROCESS_SPAWN_RIGHT,
    ExecCaptureResult,
    PipedSpawnResult,
    _decode_host_signing_key,
    _encode_host_signing_key,
    capability_issue,
    conpty_spawn_authorized,
    ensure_spawn_signing_key,
    issue_process_spawn_token,
    load_or_create_host_signing_key,
    policy_hash_argv,
    process_exec_capture_authorized,
    process_spawn_authorized,
    process_spawn_piped_authorized,
    security_clear_signing_key,
    security_set_signing_key,
    shell_chain_execute,
    shell_chain_expand,
    write_jail_check_path,
    write_jail_check_spawn,
    write_jail_clear,
    write_jail_set_roots,
)
from ._session import (
    host_session_argv,
    host_session_close,
    host_session_cwd,
    host_session_open,
    host_session_open_authorized,
    host_session_run,
    host_session_split,
    host_session_wrap,
    issue_host_session_token,
)
from ._uia import (
    a11y_snapshot,
    uia_available,
    uia_control_snapshot,
    uia_element_action,
    uia_focused_element,
    uia_read_window_text,
)

# Mirrored by ``_policy._set_signing_ready`` for monkeypatchable tests.
_signing_key_ready = False

__all__ = [
    "STATUS_OK",
    "STATUS_INVALID_ARGUMENT",
    "STATUS_ACCESS_DENIED",
    "STATUS_OPERATION_FAILED",
    "STATUS_UNSUPPORTED",
    "MOUSE_LEFT",
    "MOUSE_RIGHT",
    "MOUSE_MIDDLE",
    "WINDOW_MINIMIZE",
    "WINDOW_MAXIMIZE",
    "WINDOW_RESTORE",
    "WINDOW_CLOSE",
    "WINDOW_MOVE_RESIZE",
    "WAIT_FOREVER",
    "CONPTY_PIPE_STDIN",
    "CONPTY_PIPE_STDOUT",
    "CAPABILITY_TOKEN_SIZE",
    "PROCESS_SPAWN_RIGHT",
    "OWNER_CHECKPOINT_RIGHT",
    "DEFAULT_SPAWN_SUBJECT",
    "DEFAULT_SPAWN_SCOPE",
    "HostError",
    "Capture",
    "ExecCaptureResult",
    "PipedSpawnResult",
    "_lib",
    "_find_rg",
    "_python_exe",
    "_pwsh_exe",
    "_decode_host_signing_key",
    "_encode_host_signing_key",
    "_signing_key_ready",
    "available",
    "dpi_awareness_enable",
    "virtual_screen_rect",
    "list_monitors",
    "capture_virtual_screen",
    "capture_region",
    "print_window",
    "encode_png",
    "mouse_move",
    "mouse_click",
    "mouse_button",
    "mouse_drag",
    "mouse_scroll",
    "type_text",
    "key_combo",
    "key_hold",
    "vk_key_scan",
    "list_windows",
    "window_class",
    "window_rect",
    "foreground_window",
    "focus_window",
    "manage_window",
    "find_child_hwnd",
    "clipboard_get_text",
    "clipboard_set_text",
    "process_spawn_hidden",
    "process_wait",
    "process_kill_tree",
    "process_close",
    "uia_available",
    "uia_control_snapshot",
    "uia_read_window_text",
    "uia_focused_element",
    "uia_element_action",
    "a11y_snapshot",
    "host_op_prepare",
    "translate_posix_to_host",
    "looks_like_powershell",
    "rewrite_posix_argv",
    "conpty_available",
    "conpty_spawn",
    "conpty_write",
    "conpty_read",
    "conpty_poll",
    "conpty_kill",
    "conpty_close_pipe",
    "conpty_close",
    "_HandleStream",
    "_ConPTYProcess",
    "_spawn_conpty_sync",
    "spawn_conpty",
    "spawn_conpty_process",
    "spawn_conpty_supported",
    "security_set_signing_key",
    "security_clear_signing_key",
    "load_or_create_host_signing_key",
    "ensure_spawn_signing_key",
    "policy_hash_argv",
    "capability_issue",
    "issue_process_spawn_token",
    "write_jail_set_roots",
    "write_jail_clear",
    "write_jail_check_path",
    "write_jail_check_spawn",
    "shell_chain_expand",
    "shell_chain_execute",
    "process_spawn_authorized",
    "process_spawn_piped_authorized",
    "process_exec_capture_authorized",
    "conpty_spawn_authorized",
    "host_session_wrap",
    "host_session_split",
    "host_session_argv",
    "issue_host_session_token",
    "host_session_open",
    "host_session_open_authorized",
    "host_session_run",
    "host_session_cwd",
    "host_session_close",
    "diagnose_host_failure",
    "dialect_probe",
    "dialect_load",
    "dialect_record_success",
    "dialect_format_line",
    "resolve_which",
    "default_script_lang",
    "stretch_home",
    "stretch_load",
    "stretch_needs",
    "stretch_format_line",
    "stretch_format_whoami",
    "native",
]


def native() -> ModuleType:
    """Return the desktop module for this OS (``desktop_win`` / ``desktop_common``)."""
    if sys.platform == "win32":
        from remedy.core.computer import desktop_win as win

        return win
    from remedy.core.computer import desktop_common as posix

    return posix
