"""Shared loop-module name binding for extracted ReAct step modules.

Tests patch ``remedy.core.react_loop.loop.<name>`` — callers must resolve
names from that module at call time (not via a static import of the original).
"""

from __future__ import annotations

import sys
from typing import Any

# Names resolved from ``remedy.core.react_loop.loop`` for step modules.
LOOP_BIND_NAMES: tuple[str, ...] = (
    "aiohttp",
    "LlmBinding",
    "get_llm_binding",
    "set_llm_binding",
    "build_step_request_body",
    "apply_build_engine_after_batch",
    "_turn_tier_of",
    "_resolve_and_apply_tools_fn",
    "_wait_rmb_ready_abortable",
    "consume_llm_http_response",
    "sanitize_chat_body",
    "repair_reasoning_content_in_messages",
    "repair_tool_arguments_in_messages",
    "strip_broken_tool_call_turns",
    "_sleep_abortable",
    "_http_session",
    "_log_llm",
    "_stopped_note",
    "_take_nudges",
    "_steer_message",
    "_browse_tool_ok",
    "execute_tool_calls",
    "_provider_bits_fn",
    "_rearm_agency_tools_fn",
    "_RATE_LIMIT_MAX_RETRIES",
    "_is_rate_limited",
    "_pace_before_request",
    "_rate_limit_wait",
    "_await_or_abort",
    "inject_phase_nudge",
    "record_tool_batch_stats",
    "_is_billing_llm_api_error",
    "_is_fatal_llm_api_error",
    "_is_thinking_tool_choice_error",
    "fatal_billing_error_message",
    "fatal_model_error_message",
    "repeated_provider_error_message",
    "_TOOL_RESULT_CHAR_CAP",
    "_looks_like_pseudo_tools",
    "_parse_pseudo_tool_calls",
    "_tool_call_fingerprint",
    "agency_rearm_nudge_message",
    "agency_tool_promise_claim",
    "batch_has_approval_required",
    "batch_has_empty_or_spam_write",
    "batch_has_empty_search",
    "batch_has_tool_errors",
    "clip_appended_source_dump",
    "collapse_repeated_sentences",
    "epoch_continue_message",
    "is_serial_explore_batch",
    "looks_like_false_progress",
    "looks_like_leaked_scratchpad",
    "looks_like_safety_refusal",
    "message_asks_to_stop",
    "mission_verify_gate_message",
    "post_tools_user_summary_nudge",
    "recovery_nudge_message",
    "speed_batch_nudge_message",
    "strip_stream_status_noise",
    "strip_tool_markup",
    "turn_has_unfinished_work",
    "unfinished_work_blocks_final",
    "unfinished_work_hard_stop_message",
    "unfinished_work_nudge_message",
    "StreamRoundState",
    "build_assistant_api_message",
    "ensure_tool_call_pairings",
    "filter_fresh_tool_calls",
    "finalize_round_text",
    "normalize_tool_calls",
    "_current_abort_event",
    "set_turn_force_tool_choice",
    "set_turn_thinking_level",
    "set_turn_tool_choice_required_blocked",
    "turn_max_react_steps",
    "turn_sleev_force_direct",
    "turn_thinking_level",
    "logger",
    "json",
    "time",
    "asyncio",
    "suppress",
)

# Mutable turn state mirrored on bag ``s``.
STATE_NAMES: tuple[str, ...] = (
    "run_until_done",
    "build_state",
    "turn",
    "plan_mode",
    "attachments",
    "session_id",
    "message",
    "runtime",
    "prep",
    "boot",
    "messages",
    "history",
    "all_tools",
    "tools",
    "browse_pre_url",
    "clear_goals_only",
    "pure_action_kick",
    "open_only_browse",
    "page_interaction",
    "seen_fps",
    "result_cache",
    "produced_user_text",
    "pseudo_recovery_done",
    "pseudo_nudge_count",
    "false_progress_nudge_count",
    "zero_tools_hard_block_count",
    "mono_fp_last",
    "mono_fp_hits",
    "mono_explore_injected",
    "scratchpad_nudge_count",
    "tools_executed_this_turn",
    "recovery_nudge_done",
    "speed_batch_nudge_done",
    "serial_explore_streak",
    "_bind",
    "_adapter",
    "headers",
    "endpoint",
    "_sleev_route",
    "_connect_s",
    "timeout",
    "max_length_continuations",
    "_b0",
    "length_continuations",
    "reasoning_repair_done",
    "tool_args_repair_done",
    "tool_args_strip_done",
    "api_soft_failures",
    "max_api_soft_failures",
    "force_answer_sticky",
    "force_answer_api_fail_once",
    "force_answer_nudge_done",
    "empty_answer_retries",
    "max_empty_answer_retries",
    "_b1",
    "agency_rearm_count",
    "max_agency_rearms",
    "zero_tool_drive_count",
    "max_zero_tool_drives",
    "open_work_continues",
    "max_open_work_continues",
    "open_work_last_score",
    "open_work_last_batches",
    "finish_everything_requested",
    "_st_ow",
    "step_wall_checkpointed",
    "thinking_choice_repaired",
    "green_gate_reopen_count",
    "max_green_gate_reopens",
    "open_drive_patience",
    "last_progress_score",
    "last_progress_step",
    "open_drive_stalled_notified",
    "auth_refresh_done",
    "max_total",
    "epoch_size",
    "auto_continue",
    "max_stale_epochs",
    "epoch_index",
    "productive_in_epoch",
    "tool_batches_in_epoch",
    "stale_epochs",
    "tool_batches_this_turn",
    "open_tasks_for_wall",
    "user_wants_stop",
    "assistant_text_acc",
    "no_progress_steps",
    "last_progress_fingerprint",
    "max_no_progress_steps",
    "stalled_finalize",
    "all_error_batches",
    "max_all_error_batches",
    "failed_tools_this_turn",
    "max_failed_tools",
    "force_answer",
    "is_final_step",
    "step_tools",
    "use_openai_sse",
    "collected",
    "round_state",
    "content_parts",
    "reasoning_parts",
    "sid_mm",
    "_verify_green",
    "_keep_after_green",
    "is_disconnect_error",
    "mid_turn_fit_messages",
    "synthesize_from_tools",
    "TurnState",
    "effective_stale_epochs",
    "body",
    "stream_live",
    "text_out",
    "tool_calls_list",
    "reasoning_out",
    "stutter_src",
)


def bind_loop_module() -> dict[str, Any]:
    """Return patched callables/constants from the loop module."""
    loop_mod = sys.modules["remedy.core.react_loop.loop"]
    return {name: getattr(loop_mod, name) for name in LOOP_BIND_NAMES}


def bind_loop_tuple() -> tuple[Any, ...]:
    """Positional binds matching ``LOOP_BIND_NAMES`` (call-time loop lookup)."""
    loop_mod = sys.modules["remedy.core.react_loop.loop"]
    return tuple(getattr(loop_mod, name) for name in LOOP_BIND_NAMES)

def unpack_state(s: Any) -> dict[str, Any]:
    """Read mutable turn state from bag ``s``."""
    return {name: getattr(s, name, None) for name in STATE_NAMES}


def pack_state(s: Any, local_ns: dict[str, Any]) -> None:
    """Write mutable locals back onto bag ``s``."""
    skip = set(LOOP_BIND_NAMES) | {
        "s",
        "_lb",
        "http",
        "step",
        "helpers",
        "work_unfinished",
        "loop_mod",
        "L",
        "_k",
        "_v",
        "_ftok",
        "_st",
        "_pack_before_finals",
        "_unpack_after_finals",
    }
    for key, val in local_ns.items():
        if key in skip or key.startswith("__"):
            continue
        if callable(val) and not isinstance(val, type) and key.startswith("_"):
            continue
        setattr(s, key, val)
